### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ODyckhoff** [ravenscroftj/nerdsocial#1]
I tried running the code and it doesn't work, do I need to use Windows Powerpoint? Please help guyz I need to make myself look lik a super 1337 haxxer to impress all my friends

```
[owen@tegwen ~]$ ./README
./README: line 1: NERDSOCIAL: command not found
./README: line 2: ==========: command not found
./README: line 4: 1.: command not found
./README: line 5: --------------: command not found
./README: line 7: unexpected EOF while looking for matching `''
./README: line 13: syntax error: unexpected end of file
```

**Comment by dafrancis** [comment]
I've added nerdsocial.py. It should have all the features that nerdsocial needs

https://github.com/ravenscroftj/nerdsocial/commit/2d1f23abd6ca2d4e28041c4bb8cf5da1e3dd92f7
